// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import info.hermiths.lbesdk.model.proto.IMMsg

@kotlin.jvm.JvmName("-initializeagentUserJoinSessionMsg")
public inline fun agentUserJoinSessionMsg(block: AgentUserJoinSessionMsgKt.Dsl.() -> kotlin.Unit): IMMsg.AgentUserJoinSessionMsg =
  AgentUserJoinSessionMsgKt.Dsl._create(IMMsg.AgentUserJoinSessionMsg.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `AgentUserJoinSessionMsg`
 */
public object AgentUserJoinSessionMsgKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.AgentUserJoinSessionMsg.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.AgentUserJoinSessionMsg.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.AgentUserJoinSessionMsg = _builder.build()

    /**
     * ```
     * 客服用户名
     * ```
     *
     * `string username = 1;`
     */
    public var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.username
      @JvmName("setUsername")
      set(value) {
        _builder.username = value
      }
    /**
     * ```
     * 客服用户名
     * ```
     *
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.AgentUserJoinSessionMsg.copy(block: AgentUserJoinSessionMsgKt.Dsl.() -> kotlin.Unit): IMMsg.AgentUserJoinSessionMsg =
  AgentUserJoinSessionMsgKt.Dsl._create(this.toBuilder()).apply { block() }._build()

