// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import info.hermiths.lbesdk.model.proto.IMMsg

@kotlin.jvm.JvmName("-initializejoinResp")
public inline fun joinResp(block: JoinRespKt.Dsl.() -> kotlin.Unit): IMMsg.JoinResp =
  JoinRespKt.Dsl._create(IMMsg.JoinResp.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `JoinResp`
 */
public object JoinRespKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.JoinResp.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.JoinResp.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.JoinResp = _builder.build()

    /**
     * `string sessionId = 1;`
     */
    public var sessionId: kotlin.String
      @JvmName("getSessionId")
      get() = _builder.sessionId
      @JvmName("setSessionId")
      set(value) {
        _builder.sessionId = value
      }
    /**
     * `string sessionId = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `string serverId = 2;`
     */
    public var serverId: kotlin.String
      @JvmName("getServerId")
      get() = _builder.serverId
      @JvmName("setServerId")
      set(value) {
        _builder.serverId = value
      }
    /**
     * `string serverId = 2;`
     */
    public fun clearServerId() {
      _builder.clearServerId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.JoinResp.copy(block: JoinRespKt.Dsl.() -> kotlin.Unit): IMMsg.JoinResp =
  JoinRespKt.Dsl._create(this.toBuilder()).apply { block() }._build()

