// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import info.hermiths.lbesdk.model.proto.IMMsg

@kotlin.jvm.JvmName("-initializekickOffLineMsg")
public inline fun kickOffLineMsg(block: KickOffLineMsgKt.Dsl.() -> kotlin.Unit): IMMsg.KickOffLineMsg =
  KickOffLineMsgKt.Dsl._create(IMMsg.KickOffLineMsg.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `KickOffLineMsg`
 */
public object KickOffLineMsgKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.KickOffLineMsg.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.KickOffLineMsg.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.KickOffLineMsg = _builder.build()

    /**
     * `string userID = 1;`
     */
    public var userID: kotlin.String
      @JvmName("getUserID")
      get() = _builder.userID
      @JvmName("setUserID")
      set(value) {
        _builder.userID = value
      }
    /**
     * `string userID = 1;`
     */
    public fun clearUserID() {
      _builder.clearUserID()
    }

    /**
     * `string identityID = 2;`
     */
    public var identityID: kotlin.String
      @JvmName("getIdentityID")
      get() = _builder.identityID
      @JvmName("setIdentityID")
      set(value) {
        _builder.identityID = value
      }
    /**
     * `string identityID = 2;`
     */
    public fun clearIdentityID() {
      _builder.clearIdentityID()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.KickOffLineMsg.copy(block: KickOffLineMsgKt.Dsl.() -> kotlin.Unit): IMMsg.KickOffLineMsg =
  KickOffLineMsgKt.Dsl._create(this.toBuilder()).apply { block() }._build()

