// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msggateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import info.hermiths.lbesdk.model.proto.IMMsg

@kotlin.jvm.JvmName("-initializemsgEntityToFrontEnd")
public inline fun msgEntityToFrontEnd(block: MsgEntityToFrontEndKt.Dsl.() -> kotlin.Unit): IMMsg.MsgEntityToFrontEnd =
  MsgEntityToFrontEndKt.Dsl._create(IMMsg.MsgEntityToFrontEnd.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `MsgEntityToFrontEnd`
 */
public object MsgEntityToFrontEndKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: IMMsg.MsgEntityToFrontEnd.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: IMMsg.MsgEntityToFrontEnd.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): IMMsg.MsgEntityToFrontEnd = _builder.build()

    /**
     * `.MsgType msgType = 1;`
     */
    public var msgType: IMMsg.MsgType
      @JvmName("getMsgType")
      get() = _builder.msgType
      @JvmName("setMsgType")
      set(value) {
        _builder.msgType = value
      }
    public var msgTypeValue: kotlin.Int
      @JvmName("getMsgTypeValue")
      get() = _builder.msgTypeValue
      @JvmName("setMsgTypeValue")
      set(value) {
        _builder.msgTypeValue = value
      }
    /**
     * `.MsgType msgType = 1;`
     */
    public fun clearMsgType() {
      _builder.clearMsgType()
    }

    /**
     * `.State state = 2;`
     */
    public var state: IMMsg.State
      @JvmName("getState")
      get() = _builder.state
      @JvmName("setState")
      set(value) {
        _builder.state = value
      }
    /**
     * `.State state = 2;`
     */
    public fun clearState() {
      _builder.clearState()
    }
    /**
     * `.State state = 2;`
     * @return Whether the state field is set.
     */
    public fun hasState(): kotlin.Boolean {
      return _builder.hasState()
    }

    public val MsgEntityToFrontEndKt.Dsl.stateOrNull: IMMsg.State?
      get() = _builder.stateOrNull

    /**
     * `.MsgBody msgBody = 3;`
     */
    public var msgBody: IMMsg.MsgBody
      @JvmName("getMsgBody")
      get() = _builder.msgBody
      @JvmName("setMsgBody")
      set(value) {
        _builder.msgBody = value
      }
    /**
     * `.MsgBody msgBody = 3;`
     */
    public fun clearMsgBody() {
      _builder.clearMsgBody()
    }
    /**
     * `.MsgBody msgBody = 3;`
     * @return Whether the msgBody field is set.
     */
    public fun hasMsgBody(): kotlin.Boolean {
      return _builder.hasMsgBody()
    }

    public val MsgEntityToFrontEndKt.Dsl.msgBodyOrNull: IMMsg.MsgBody?
      get() = _builder.msgBodyOrNull

    /**
     * `.CreateSessionMsg createSessionMsg = 4;`
     */
    public var createSessionMsg: IMMsg.CreateSessionMsg
      @JvmName("getCreateSessionMsg")
      get() = _builder.createSessionMsg
      @JvmName("setCreateSessionMsg")
      set(value) {
        _builder.createSessionMsg = value
      }
    /**
     * `.CreateSessionMsg createSessionMsg = 4;`
     */
    public fun clearCreateSessionMsg() {
      _builder.clearCreateSessionMsg()
    }
    /**
     * `.CreateSessionMsg createSessionMsg = 4;`
     * @return Whether the createSessionMsg field is set.
     */
    public fun hasCreateSessionMsg(): kotlin.Boolean {
      return _builder.hasCreateSessionMsg()
    }

    public val MsgEntityToFrontEndKt.Dsl.createSessionMsgOrNull: IMMsg.CreateSessionMsg?
      get() = _builder.createSessionMsgOrNull

    /**
     * `.AgentUserJoinSessionMsg agentUserJoinSessionMsg = 5;`
     */
    public var agentUserJoinSessionMsg: IMMsg.AgentUserJoinSessionMsg
      @JvmName("getAgentUserJoinSessionMsg")
      get() = _builder.agentUserJoinSessionMsg
      @JvmName("setAgentUserJoinSessionMsg")
      set(value) {
        _builder.agentUserJoinSessionMsg = value
      }
    /**
     * `.AgentUserJoinSessionMsg agentUserJoinSessionMsg = 5;`
     */
    public fun clearAgentUserJoinSessionMsg() {
      _builder.clearAgentUserJoinSessionMsg()
    }
    /**
     * `.AgentUserJoinSessionMsg agentUserJoinSessionMsg = 5;`
     * @return Whether the agentUserJoinSessionMsg field is set.
     */
    public fun hasAgentUserJoinSessionMsg(): kotlin.Boolean {
      return _builder.hasAgentUserJoinSessionMsg()
    }

    public val MsgEntityToFrontEndKt.Dsl.agentUserJoinSessionMsgOrNull: IMMsg.AgentUserJoinSessionMsg?
      get() = _builder.agentUserJoinSessionMsgOrNull

    /**
     * `.HasReadReceiptMsg hasReadReceiptMsg = 6;`
     */
    public var hasReadReceiptMsg: IMMsg.HasReadReceiptMsg
      @JvmName("getHasReadReceiptMsg")
      get() = _builder.hasReadReceiptMsg
      @JvmName("setHasReadReceiptMsg")
      set(value) {
        _builder.hasReadReceiptMsg = value
      }
    /**
     * `.HasReadReceiptMsg hasReadReceiptMsg = 6;`
     */
    public fun clearHasReadReceiptMsg() {
      _builder.clearHasReadReceiptMsg()
    }
    /**
     * `.HasReadReceiptMsg hasReadReceiptMsg = 6;`
     * @return Whether the hasReadReceiptMsg field is set.
     */
    public fun hasHasReadReceiptMsg(): kotlin.Boolean {
      return _builder.hasHasReadReceiptMsg()
    }

    public val MsgEntityToFrontEndKt.Dsl.hasReadReceiptMsgOrNull: IMMsg.HasReadReceiptMsg?
      get() = _builder.hasReadReceiptMsgOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun IMMsg.MsgEntityToFrontEnd.copy(block: MsgEntityToFrontEndKt.Dsl.() -> kotlin.Unit): IMMsg.MsgEntityToFrontEnd =
  MsgEntityToFrontEndKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val IMMsg.MsgEntityToFrontEndOrBuilder.stateOrNull: IMMsg.State?
  get() = if (hasState()) getState() else null

public val IMMsg.MsgEntityToFrontEndOrBuilder.msgBodyOrNull: IMMsg.MsgBody?
  get() = if (hasMsgBody()) getMsgBody() else null

public val IMMsg.MsgEntityToFrontEndOrBuilder.createSessionMsgOrNull: IMMsg.CreateSessionMsg?
  get() = if (hasCreateSessionMsg()) getCreateSessionMsg() else null

public val IMMsg.MsgEntityToFrontEndOrBuilder.agentUserJoinSessionMsgOrNull: IMMsg.AgentUserJoinSessionMsg?
  get() = if (hasAgentUserJoinSessionMsg()) getAgentUserJoinSessionMsg() else null

public val IMMsg.MsgEntityToFrontEndOrBuilder.hasReadReceiptMsgOrNull: IMMsg.HasReadReceiptMsg?
  get() = if (hasHasReadReceiptMsg()) getHasReadReceiptMsg() else null

