// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import info.hermiths.lbesdk.model.proto.test.Msg

@kotlin.jvm.JvmName("-initializehxMsgEntity")
public inline fun hxMsgEntity(block: HxMsgEntityKt.Dsl.() -> kotlin.Unit): Msg.HxMsgEntity =
  HxMsgEntityKt.Dsl._create(Msg.HxMsgEntity.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `HxMsgEntity`
 */
public object HxMsgEntityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Msg.HxMsgEntity.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: Msg.HxMsgEntity.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): Msg.HxMsgEntity = _builder.build()

    /**
     * `string user = 1;`
     */
    public var user: kotlin.String
      @JvmName("getUser")
      get() = _builder.user
      @JvmName("setUser")
      set(value) {
        _builder.user = value
      }
    /**
     * `string user = 1;`
     */
    public fun clearUser() {
      _builder.clearUser()
    }

    /**
     * `string msg = 2;`
     */
    public var msg: kotlin.String
      @JvmName("getMsg")
      get() = _builder.msg
      @JvmName("setMsg")
      set(value) {
        _builder.msg = value
      }
    /**
     * `string msg = 2;`
     */
    public fun clearMsg() {
      _builder.clearMsg()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Msg.HxMsgEntity.copy(block: HxMsgEntityKt.Dsl.() -> kotlin.Unit): Msg.HxMsgEntity =
  HxMsgEntityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

